plugins:
  - jest
  - babel
env:
  node: true
  jest: true
  browser: true
  es2021: true
extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
overrides: []
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
